spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/dbdiscovery
    username:
    password:
    hikari:
      initializationFailTimeout: 0
      maximumPoolSize: 1
      auto-commit: false
#logging:
#   level:
#     ROOT: DEBUG
